export const MODEL_ALIASES: Record<string, Record<string, string[]>> = {
  skoda: {
    // Běžné varianty generace/karoserie sloučeny do jednoho model_key pro pricing MVP.
    // RS a Scout slity pro jednotný tržní segment; později lze oddělit (skoda_octavia_rs, skoda_octavia_scout).
    octavia: [
      "octavia",
      "octavia combi",
      "octavia rs",
      "octavia iii",
      "octavia iii combi",
      "octavia scout",
    ],
    superb: ["superb", "superb combi"],
    fabia: ["fabia", "fabia combi"],
    kodiaq: ["kodiaq"],
    scala: ["scala"],
    kamiq: ["kamiq"],
  },
  volkswagen: {
    golf: ["golf"],
    // Passat: běžné varianty karoserie a generace sloučeny pro pricing MVP (variant = kombi, b7/b8 = generace).
    passat: ["passat", "passat variant", "passat b8", "passat b7"],
    tiguan: ["tiguan"],
    polo: ["polo"],
    touareg: ["touareg"],
  },
  bmw: {
    "1_series": [
      "řada 1",
      "rada 1",
      "rada 1.",
      "114i",
      "116d",
      "118d",
      "120d",
      "125d",
    ],
    "3_series": [
      "řada 3",
      "rada 3",
      "rada 3.",
      "316i",
      "316d",
      "318i",
      "318d",
      "320d",
      "320i",
      "330d",
      "330i",
      "3 touring",
    ],
    "5_series": [
      "řada 5",
      "rada 5",
      "rada 5.",
      "518d",
      "520d",
      "520i",
      "525d",
      "530d",
      "530i",
      "5 touring",
    ],
    x3: ["x3"],
    x5: ["x5"],
  },
  audi: {
    a3: ["a3"],
    a4: ["a4", "a4 avant"],
    a6: ["a6", "a6 avant"],
    q5: ["q5"],
    q7: ["q7"],
  },
  toyota: {
    corolla: ["corolla"],
    rav4: ["rav4", "rav 4"],
    yaris: ["yaris"],
  },
  ford: {
    focus: ["focus"],
    mondeo: ["mondeo"],
    kuga: ["kuga"],
    fiesta: ["fiesta"],
  },
  mercedes_benz: {
    a_class: [
      "třída a",
      "trida a",
      "tridy a",
      "tridy a.",
      "a180",
      "a200",
    ],
    b_class: [
      "třída b",
      "trida b",
      "tridy b",
      "tridy b.",
      "b180",
      "b200",
    ],
    c_class: [
      "třída c",
      "trida c",
      "tridy c",
      "tridy c.",
      "c180",
      "c200",
      "c220",
      "c300",
    ],
    e_class: [
      "třída e",
      "trida e",
      "tridy e",
      "tridy e.",
      "e220",
      "e300",
      "e400",
    ],
    cla: ["cla"],
    gls: ["gls"],
    gle: ["gle"],
    glc: ["glc"],
  },
  land_rover: {
    range_rover: ["range rover"],
    range_rover_sport: ["range rover sport"],
    discovery: ["discovery"],
    discovery_sport: ["discovery sport"],
    defender: ["defender"],
    freelander: ["freelander"],
    evoque: ["evoque", "range rover evoque"],
    velar: ["velar", "range rover velar"],
  },
  dodge: {
    ram: ["ram", "ram 1500", "ram 2500"],
  },
};

